services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pinterest_hub_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/pinterest-hub
      - JWT_SECRET=supersecretpinterestkey
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: pinterest_hub_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
